#!/bin/sh
[ -d "${1}" ] && DIRECTORY="${1}" || DIRECTORY="${HOME}"/Pictures/Screenshots

DMENU_ARGS=${@}
IMG_PATH="${DIRECTORY%/}/Screenshot_$(date '+%Y-%m-%d-(%H:%M:%S)').png"
SUCCESS_MSG="Saved screenshot in ${IMG_PATH}"
FAILED_MSG="Failed to save screenshot in ${IMG_PATH}"

notify() {
	if ! ${USING_TERMINAL}; then
		if [ -n "$(command -v herbe)" ]; then
			herbe "${1}"
		else
			printf 'ERROR: `herbe` is not installed\n'
			printf '%b\n' "${1}"
		fi
	else
		printf '%b\n' "${1}"
	fi
}


check_dir() {
	[ ! -d "${DIRECTORY}" ] && mkdir "${DIRECTORY}" ||
		notify 'Failed to create DIRECTORY' && exit
}


use_scrot() {
	read input
	case "${input}" in
		Full)
			scrot -d 0.5 "${IMG_PATH}" &&
				(notify "${SUCCESS_MSG}"; true) ||
				notify "${FAILED_MSG}"
			;;

		Partial)
			scrot -s -d 0.5 "${IMG_PATH}" &&
				(notify "${SUCCESS_MSG}"; true) ||
				notify "${FAILED_MSG}"
			;;

		*)
			notify 'Did not take screenshot'
			;;
	esac

}

use_magick() {
	read input

	case "${input}" in
		Full)
			sleep 0.5
			magick import -window root "${IMG_PATH}" &&
				(notify "${SUCCESS_MSG}"; true) ||
				notify "${FAILED_MSG}"
			;;

		Partial)
			sleep 0.5
			magick import "${IMG_PATH}" &&
				(notify "${SUCCESS_MSG}"; true) ||
				notify "${FAILED_MSG}"
			;;

		*)
			notify "Did not take screenshot"
			;;
	esac
}


main() {
	check_dir
	if [ -z "${DISPLAY}" ]; then
		notify 'ERROR: Cannot open display...\n'
	elif [ -z "$(command -v dmenu)" ]; then
		notify 'ERROR: `dmenu` is not installed...\n'
		exit
	elif [ -n "$(command -v magick)" ]; then
		printf "Full\nPartial\nCancel\n" | dmenu | use_magick
	elif [ -n "$(command -v scrot)" ]; then
		printf "Full\nPartial\nCancel\n" | dmenu | use_scrot
	else
		printf '`magick` and `scrot` are not installed, please install one of them...\n'
	fi
}
main
