#!/bin/sh
# A script to determine whether tmux exists, a tmux session exists, and to attach/create a session
# This script will NOT spawn a new terminal


if [ "${1}" = '-t' ]; then
	if command -v tmux >/dev/null; then
		${TERMINAL} -e ${0} &
		exit
	else
		${TERMINAL}
	fi
fi

if command -v tmux >/dev/null; then
	if tmux has-session 2>/dev/null; then
		tmux attach
	else
		tmux new-session -s Default
	fi
else
	${SHELL}
fi
