#!/bin/sh
fail=false
! command -v loginctl >/dev/null && printf '`loginctl`/elogind` is not in this system... Will not run\n' && fail=true
! command -v dmenu >/dev/null    && printf '`dmenu` is not in this system... Will not run' && fail=true
${fail} && exit


OPTIONS="\
 Suspend           - loginctl suspend  & herbe Suspending
 Lock              - slock
 Lock & Suspend    - slock & loginctl suspend
 Reboot            - loginctl reboot & herbe Rebooting
 Shutdown          - loginctl poweroff & herbe 'Shutting down'
 Cancel            - herbe Canceled\
"



chosen=$(
	IFS='
	'
	for opt in $OPTIONS; do
		opt="${opt% *-*}"
		printf '%b\n' "${opt%${opt##*[! ]}}"
	done | dmenu $@
)

[ -z "${chosen}" ] && chosen="Cancel"

IFS='
'
for opt in ${OPTIONS}; do
	if [ -z "${opt##$chosen*}" ]; then
		eval "${opt##* - }"
		exit
	fi
done
