#!/bin/sh
DIRECTORY="${HOME}"/Pictures/Screenshots

getopts 't' opt
[ ${opt} = t ] && DIRECTORY=/tmp/TMPScreenshots && shift

ARGS=${@}
DEP_INSTALLED=true
IMG_PATH="${DIRECTORY%/}/Screenshot_$(date '+%Y-%m-%d-(%H:%M:%S)').png"
SUCCESS_MSG="Saved screenshot in ${IMG_PATH}"
FAILED_MSG="Failed to save screenshot in ${IMG_PATH}"




notify() {
	if [ ! -t 0 ]; then
		if [ -n "$(command -v herbe)" ]; then
			herbe "${1}"
		else
			printf 'ERROR: `herbe` is not installed\n'
			printf '%b\n' "${1}"
		fi
	else
		printf '%b\n' "${1}"
	fi
}


check_dep()
{
	! command -v $1 >/dev/null && notify 'ERROR: `%s` is not installed\n' "$1" >&2
	DEP_INSTALLED=false
}


screenshot()
{
	read opt
	case "${opt}" in
		Full)
			sleep 0.5
			magick import -window root "${IMG_PATH}" &&
				(notify "${SUCCESS_MSG}"; true) ||
				notify "${FAILED_MSG}"
			;;

		Partial)
			sleep 0.5
			magick import "${IMG_PATH}" &&
				(notify "${SUCCESS_MSG}"; true) ||
				notify "${FAILED_MSG}"
			;;

		*)
			notify "Did not take screenshot"
			;;
	esac

}


main()
{
	check_dep dmenu
	check_dep magick

	${DEP_INSTALLED} && exit

	if [ ! -d "${DIRECTORY}" ]; then
		mkdir --parents "${DIRECTORY}" ||
			(notify 'Screenshot directory does not exist and failed to create directory...'; exit)
	fi

	printf 'Full\nPartial\nCancel\n' | dmenu ${ARGS} | screenshot
}
main
