#!/bin/sh
DIRECTORY="${HOME}"/Pictures/Screenshots

for arg in ${@}; do
	if [ "${arg}" = '-t' ]; then
		DIRECTORY=/tmp/screenshot_tmp
		break
	fi
done

DMENU_ARGS=$@
IMG_PATH="${DIRECTORY%/}/Screenshot_$(date '+%Y-%m-%d-(%H:%M:%S)').png"
SUCCESS_MSG="Saved screenshot in ${IMG_PATH}"
FAILED_MSG="Failed to save screenshot in ${IMG_PATH}"


notify() {
	if [ "${DISPLAY}" ]; then
		if [ "$(command -v herbe)" ]; then
			herbe "${1}"
		else
			printf 'ERROR: `herbe` is not installed\n'
			printf '%b\n' "${1}"
		fi
	else
		printf '%b\n' "${1}"
	fi
}


screenshot()
{
	case "$(printf 'Full\nPartial\nCancel\n' | dmenu -p 'Type:' ${DMENU_ARGS})" in
		Full)
			sleep 0.2
			if [ "$(command -v magick)" ]; then
				magick import -window root "${IMG_PATH}"
			elif [ "$(command -v scrot)" ]; then
				scrot "${IMG_PATH}"
			fi

			[ $? -eq 0 ] &&
				(notify "${SUCCESS_MSG}"; true) ||
				notify "${FAILED_MSG}"
			;;

		Partial)
			sleep 0.2
			if [ "$(command -v magick)" ]; then
				magick import "${IMG_PATH}"
			elif [ "$(command -v scrot)" ]; then
				scrot --select "${IMG_PATH}"
			fi

			[ $? -eq 0 ] &&
				(notify "${SUCCESS_MSG}"; true) ||
				notify "${FAILED_MSG}"
			;;

		*)
			notify "Did not take screenshot"
			;;
	esac
}


main()
{
	if [ ! "$(command -v dmenu)" ]; then
		notify 'ERROR: `dmenu` is not installed'
	fi

	if [ ! "$(command -v magick)" ] && [ ! "$(command -v scrot)" ]; then
		notify 'ERROR: `magick` and `scrot` is not installed, please install one of them'
	fi

	if [ ! -d "${DIRECTORY}" ]; then
		mkdir --parents "${DIRECTORY}" && screenshot
	else
		screenshot
	fi
}
main
