#!/bin/sh
if [ "$(command -v systemctl)" ]; then
	sys_cmd='systemctl'
elif "$(command -v loginctl)"; then
	sys_cmd='loginctl'
else
	if [ "$(command -v herbe)" ] && [ "${DISPLAY}" ]; then
		herbe 'Either `systemctl` or `loginctl` needs to be installed'
	else
		printf 'Either `systemctl` or `loginctl` needs to be installed\n'
	fi
	exit 1
fi

OPTIONS="\
 Suspend           - ${sys_cmd} suspend & herbe Suspending
 Lock              - slock
 Lock & Suspend    - slock & ${sys_cmd} suspend
 Reboot            - ${sys_cmd} reboot & herbe Rebooting
 Shutdown          - ${sys_cmd} poweroff
 Cancel            - herbe Canceled\
"


main()
(
	IFS='
	'

	chosen="$(
		for opt in ${OPTIONS}; do
			opt=${opt%%- *}
			opt=${opt%${opt##*[! ]}}
			printf '%b\n' "${opt}"
		done | dmenu ${@}
	)"

	[ ! "${chosen}" ] && return
	for opt in ${OPTIONS}; do
		if [ ! "${opt##${chosen}*}" ]; then
			cmd="${opt#*- }"
			break
		fi
	done

	eval "${cmd}"
)
main ${@}
