#!/bin/sh
xrandr --output $(xrandr | grep -Po '.*(?= connected)') --mode 1360x768 --scale 1.2

hsetroot -cover ~/.local/rice/Wallpapers/"Rock Thing.png"

setxkbmap -option keypad:pointerkeys
xset r rate 250 50
xrdb ~/.config/X11/Xresources

export WINIT_X11_SCALE_FACTOR=1

# Turn of screen saver and dpms
xset s off -dpms

xcompmgr &
(dwmblocks &) ; exec dwm
