#!/bin/bash
# Simple aliases
alias cman="connmanctl"
alias e="$EDITOR"


# Default options
alias ytmp3="youtube-dl --extract-audio --audio-format mp3"
alias emacs="emacs -nw"
alias mkdir="mkdir -pv"
alias diff="diff --color=always"
alias grep="grep --color=auto"
alias wget='wget --hsts-file="/tmp/cache/wget-hsts"'
alias sxiv="sxiv -o"
alias ls="ls --color --group-directories-first"
alias mv="mv -i"
alias rm="rm -i"
alias cp="cp -i"
alias ip="ip --color=auto"

# Bookmarks
alias gscr='cd "${HOME}"/.config/scripts/; ls'
alias grice='cd "${HOME}"/.local/rice; ls'

# Extra functionality
alias makepkgmem="BUILDDIR=/tmp/makepkg makepkg"
alias parumem="paru --clonedir /tmp/makepkg"
alias sx='startx ${HOME}/.config/X11/xinitrc'
