#!/bin/bash
# Simple aliases
alias cman="connmanctl"
alias e="$EDITOR"


# Default options
alias ytmp3="youtube-dl --extract-audio --audio-format mp3"
alias mkdir="mkdir -pv"
alias grep="grep --color=auto"
alias diff="diff --color=always"
alias ls="ls --color --group-directories-first"
alias mv="mv -i"
alias rm="rm -I"
alias cp="cp -i"
alias ip="ip --color=auto"

alias sxiv="sxiv -o"

# Bookmarks
alias scr="cd ~/.config/scripts/; ls"

# Extra functionality
alias makepkgmem="BUILDDIR=/tmp/makepkg makepkg"
alias parumem="paru --clonedir /tmp/makepkg"
alias sx="startx ~/.config/X11/xinitrc"
