#!/bin/sh


fetches='
screenfetch https://github.com/KittyKatt/screenFetch/raw/master/screenfetch-dev bash
neofetch    https://github.com/dylanaraps/neofetch/raw/master/neofetch          bash
pfetch      https://github.com/dylanaraps/pfetch/raw/master/pfetch              sh
'

old_ifs=${IFS}

IFS='
'
for fetch in ${fetches}; do
	prog="${fetch%% *}"

	command -v ${prog} >/dev/null && continue

	shell="${fetch##* }"
	url="${fetch#* }"
	url="${url% *}"

	if command -v curl >/dev/null; then
		eval "alias ${prog}='curl -L --silent "${url}" | ${shell} -s'"
	elif command -v wget >/dev/null; then
		eval "alias ${prog}='wget -qO- "${url}" | ${shell} -s'"
	fi
done
IFS=${old_ifs}
