#!/bin/sh
# Basic interactive shell config that should work on every posix compliant shell
set -o vi   # Vi mode, works on most shells
[ "$(command -v stty)" ] && stty -ixon 	# Disable Ctrl-q and Ctrl-s
export HISTFILE=/tmp/shell_history


# Shell Options #
if [ "${BASH_VERSION}" ]; then
	# Bash Specific configuration
	complete -c man which
	complete -cf sudo
	shopt -s autocd
	shopt -s checkwinsize

	[ -f /usr/share/bash-completion/bash_completion ] &&
		. /usr/share/bash-completion/bash_completion
elif [ "${ZSH_NAME}" ]; then
	# Zsh Specific configuration
	setopt autocd
	bindkey -v '^H' backward-delete-char
	bindkey -v '^?' backward-delete-char
	setopt PROMPT_SUBST
fi



# PROMPT #
# Should work on dash, bash, zsh, and ksh
print_prompt() {
	ret=${?}
	symbol=">"
	color=true
	if [ "${BASH_VERSION}" ]; then
		wrapper_start="\001"
		wrapper_end="\002"
	elif [ "${ZSH_NAME}" ]; then
		wrapper_start="%{"
		wrapper_end="%}"
	elif ! [ "${KSH_VERSION}" ]; then
		color=false
		unset reset color_dir color_branch color_failed color_success
	fi

	if ${color}; then
		reset="${wrapper_start}\033[0m${wrapper_end}"
		color_dir="${wrapper_start}\033[38;5;11m${wrapper_end}"
		color_branch="${wrapper_start}\033[38;5;4m${wrapper_end}"
		color_failed="${wrapper_start}\033[38;5;1m${wrapper_end}"
		color_success="${wrapper_start}\033[38;5;6m${wrapper_end}"
	fi

	tmp="$(tty)"


	if [ "${wrapper+x}" ]; then
		for var in reset color_dir color_branch color_failed color_success; do
			eval "${var}=\"\${wrapper_start}\$${var}\${wrapper_end}\""
		done
	fi

	# Change the directory color to red if the user doesn't have permissions to
	# write to the directory
	[ -w "${PWD}" ] || color_dir=${color_failed}

	# Current Directory
	if ! [ "${PWD%${HOME}*}" ]; then
		printf '%b%s' "${color_dir}" "~${PWD#${HOME}}"
	else
		printf '%b%s' "${color_dir}" "${PWD}"
	fi

	# Git Branch
	branch=$(git branch --show-current 2>/dev/null)
	[ "${branch}" ] && printf '%b [ %s ]' "${color_branch}" "${branch}"

	# Symbol color
	if [ ${ret} -eq 0 ]; then
		printf '\n%b%s%b ' "${color_success}" "${symbol}" "${reset}"
	else
		printf '\n%b%s%b ' "${color_failed}" "${symbol}" "${reset}"
	fi
}
export PS1="\$(print_prompt)"



# ALIASES #
alias emacs="emacs -nw"
alias mkdir="mkdir -pv"
alias diff="diff --color=always"
alias grep="grep --color=auto"
alias wget='wget --hsts-file="/tmp/wget-hsts"'
alias sxiv="sxiv -o"
alias smeuesic="printf '%s\n' 'https://www.youtube.com/playlist?list=PLRV1hc8TIW-7znQIWaVarxdUxf7lskmBc'"
alias ls="ls --color --group-directories-first"
alias mv="mv -i"
alias rm="rm -i"
alias cp="cp -i"
alias ip="ip --color=auto"
alias dit="git --git-dir=${HOME}/.local/dots --work-tree=${HOME}"

droidcam_ip="192.168.18.51"
droidcam_port="4747"
alias dra="droidcam-cli -a ${droidcam_ip} ${droidcam_port}"
alias drav="droidcam-cli -a -v ${droidcam_ip} ${droidcam_port}"
unset droidcam_ip droidcam_port



# FUNCTIONS #
compress_documents() {
	if [ -d "${HOME}/Documents" ]; then
		printf "[\033[1;31mERROR\033[0m] '%s' does not exist\n" "${HOME}/Documents" >&2
		return
	fi

	if [ "$(command -v tar)" ]; then
		printf "[\033[1;31mERROR\033[0m] Command 'tar' not found\n" >&2
		return
	fi

	printf "Compressing '%s' to %s\n" "${HOME}/Documents" "${HOME}/Documents.tar.gz"
	tar cvf Documents.tar.gz ~/Documents -I "gzip --best"
}


fix-time() {
	# Fix time desync in Linux
	err=false
	for dep in ntpd hwclock sudo; do
		[ "$(command -v ${dep})" ] && continue
		printf "[\033[1;31mERROR\033[0m] Command '${dep}' not found\n" >&2
		err=true
	done
	${err} && return 1
	printf "Running 'ntpd -qg; hwclock --systohc'\n"
	sudo "${SHELL}" -c  'ntpd -qg; hwclock --systohc'
}


colors() {
	# Print terminal colors
	if ! [ "${1##*[!0-9]*}" ]; then
		printf "[\033[1;31mERROR\033[0m] Not an integer\n" >&2
		return 1
	elif [ ${1} -gt 255 ]; then
		printf "[\033[1;31mERROR\033[0m] Number is greater than 255\n" >&2
		return 1
	fi

	i=0
	case "${1}" in
		"16") printf '\n'
			  while [ ${i} -ne 16 ]; do
				  [ ${i} -eq 8 ] && printf '\n\n'
				  printf "\033[7m\033[38;5;${i}m  \033[0m "
				  i=$((i + 1))
			  done
			  printf '\n'
			  ;;
		*) while [ ${i} -ne ${1} ]; do
			   printf "\033[7m\033[38;5;${i}m ${i} \033[0m"
			   i=$((i + 1))
		   done
		   ;;
	esac
	printf '\n'
	unset i
}


doar() { eval "su -c '$@'"; }


jmtpfs-auto-mount() {
	if ! [ "$(command -v jmtpfs)" ]; then
		printf "[\033[1;31mERROR\033[0m] Command 'jmtpfs' not found\n" >&2
		return 1
	fi

	if ! jmtpfs -l | { read _; read line; [ "${line}" ]; }; then
		printf "[\033[1;31mERROR\033[0m] No devices found\n" >&2
		return 1
	fi

	if ! [ -d "/tmp/jmtpfs" ]; then
		mkdir "/tmp/jmtpfs"
		jmtpfs "/tmp/jmtpfs"
	else
		umount "/tmp/jmtpfs"
		rmdir "/tmp/jmtpfs"
	fi
}


sx() {
	# Start x server
	xinitrc="${HOME}/.config/X11/xinitrc "
	if [ -f "${xinitrc}" ]; then
		startx "${xinitrc}"
	else
		startx
	fi
}


e() {
	if [ "${EDITOR}" = "emacs" ] && [ "$(command -v emacsclient)" ]; then
		emacsclient -a ${EDITOR} $@ &
	else
		${EDITOR} $@
	fi
}


# MISC #
# Git
[ "$(git config --get-regexp ^alias\.graph)" ] ||
	git config --global alias.graph "log --graph --oneline"

# Less
export LESS_TERMCAP_mb=$'\033[1;32m'
export LESS_TERMCAP_md=$'\033[1;32m'
export LESS_TERMCAP_so=$'\033[1;33m'
export LESS_TERMCAP_me=$'\033[0m'
export LESS_TERMCAP_se=$'\033[0m'
export LESS_TERMCAP_ue=$'\033[0m'
export LESS_TERMCAP_us=$'\033[1;4;31m'

# Nix
[ -f "${HOME}/.nix-profile/etc/profile.d/nix.sh" ] &&
	. "${HOME}/.nix-profile/etc/profile.d/nix.sh"

# Brew
[ -f "/home/linuxbrew/.linuxbrew/bin/brew" ] &&
	eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"



if ! [ "${TERM}" = "linux" ]; then
	printf '\r\033[H\033[J'
	colors 16
fi
