#!/bin/sh
# "Less" coloring
lessColors() {
	export LESS_TERMCAP_mb=$'\033[1;32m'
	export LESS_TERMCAP_md=$'\033[1;32m'
	export LESS_TERMCAP_me=$'\033[0m'
	export LESS_TERMCAP_se=$'\033[0m'
	export LESS_TERMCAP_so=$'\033[01;33m'
	export LESS_TERMCAP_ue=$'\033[0m'
	export LESS_TERMCAP_us=$'\033[1;4;31m'
}
lessColors
unset lessColors


# fzf coloring
fzf_config() {
	! command -v fzf >/dev/null && return

	color1=11
	color2=3
	export FZF_DEFAULT_OPTS="
		--color fg:15,bg:-1,hl:${color1},fg+:15,bg+:-1,hl+:${color2}
		--color info:${color2},prompt:${color2},spinner:${color2}
		--color pointer:${color2},marker:${color2},header:${color2}
	"
	export FZF_DEFAULT_COMMAND="find . -type d \
	\( -name 'BraveSoftware' -o -path '*/dots/*' -o -path '*/.git/*' -o -path '*/_cacache/*' -o -path '*coc*' -o -path '*.cache*' \) \
	-prune -false -o -name '*'"

	unset color1
	unset color2
}
fzf_config; unset fzf_config


nnn_config() {
	if command -v nnn >/dev/null; then
		export NNN_PLUG="g:getplugs;p:preview-tui;m:nmount"
		export NNN_BMS='d:~/Documents;t:/tmp;r:~/.local/rice'

		BLK="0B" CHR="0B" DIR="04" EXE="02" REG="00" HARDLINK="05" SYMLINK="06" MISSING="07" ORPHAN="09" FIFO="06" SOCK="03" OTHER="06"
		export NNN_FCOLORS="$BLK$CHR$DIR$EXE$REG$HARDLINK$SYMLINK$MISSING$ORPHAN$FIFO$SOCK$OTHER"
		export NNN_OPENER=openf
	fi
}
nnn_config; unset nnn_config


if [ ! -f "$XDG_CONFIG_HOME"/git/config ]; then
	mkdir --parent "$XDG_CONFIG_HOME"/git
	touch "$XDG_CONFIG_HOME"/git/config
fi


if command -v ueberzug >/dev/null; then
	export UEBERZUG_FIFO=/tmp/ueberzug-fifo
fi
