#!/bin/sh
# Prompt should work in bash, zsh, AND ksh

print_prompt() {


	ret=$?
	dir_col=$'\033[38;5;11m'
	success_col=$'\033[38;5;2m'
	failed_col=$'\033[38;5;1m'
	branch_col=$'\033[38;5;3m'
	cur_dir=${PWD}
	if [ -z "${cur_dir##${HOME}*}" ]; then
		cur_dir="~${cur_dir##${HOME}}"
	fi

	printf '\001\033[1m\002\001%b\002%s' "${dir_col}" "${cur_dir}"

	if command -v git >/dev/null; then
		branch="$(git branch 2>/dev/null)"
		old_ifs=${IFS}
		IFS='
		'
		for line in "${branch}"; do
			if [ -z "${branch}" ]; then
				break
			fi

			if [ -z "${line##[*]*}" ]; then
				printf '\001%b\002 [ %s ]' "${branch_col}" "${line##[*] }"
				break
			fi
		done
	fi
	IFS=${old_ifs}

	if [ ${ret} -eq 0 ]; then
		printf '\n\001%b\002>\001\033[0m\002 ' "${success_col}"
	else
		printf '\n\001%b\002>\001\033[0m\002 ' "${failed_col}"
	fi

	unset branch
	unset old_ifs
	unset cur_dir
	unset ret
	unset dir_col
	unset success_col
	unset failed_col
	unset branch_col
}


if [ "${ZSH_NAME}" ]; then
	setopt PROMPT_SUBST
fi

PS1="\$(print_prompt)"
export PS1
