#!/bin/sh
# ------------------------------------------------
# Script Name    - smeuesic
# Author Name    - Smeueg
# Author Email   - Smeueg@gmail.com
# Author Gitlab  - https://gitlab.com/Smeueg
# Sun 20 Mar 12:01:39 WIB 2022
# ------------------------------------------------
# TODO:
# Automatically remove files that aren't in the youtube playlist
#
#
# Download the mp3 of videos in a playlist
# Change the value `pl_url` to the playlist url that you want


music_dir="${HOME}/Music"
pl_url="https://www.youtube.com/playlist?list=PLRV1hc8TIW-7znQIWaVarxdUxf7lskmBc"

# Check if youtube-dl is installed
[ "$(command -v youtube-dl)" ] || {
	printf '\033[1m\033[31m[ERROR]\033[0m `youtube-dl` is not installed'
	exit 1
}

# A replacement for `sed`
replace() { # Arguments: <string> <query> <substitution>
	string="${1}"
	query="${2}"
	substitution="${3}"

	while ! [ "${string%%*${query}*}" ]; do
		string="${string%%${query}*}${substitution}${string#*${query}}"
	done
	echo "${string}"
}

# Check if ${music_dir} exist as a directory
[ -d "${music_dir}" ] || {
	printf '\033[1m\033[32m[NOTICE] "%s" does not exit, create? [Y\\n] ' "${music_dir}"

	read input
	case "${input}" in
		[Yy][Ee][Ss]|[Yy]|"") ;;
		*) printf 'Exiting...\n' && exit 1 ;;
	esac
	mkdir -pv "${music_dir}"
}


# Header
[ ${COLUMNS} -le 80 ]
cols=${COLUMNS}

len=$((${cols:-80} / 2 - 7))
while [ ${#str} -lt ${len} ]; do
	str="${str}="
done
printf '%s Getting Urls %s' "${str}" "${str}"


# Downloading Music
while read title; do
	read id
	title=$(replace "${title}" "/" "\\")

	url="https://www.youtube.com/watch?v=${id}"
	[ -f "${music_dir}/${title}.mp3" ] ||
		youtube-dl "${url}" \
		 		   -x \
		 		   --audio-format mp3 \
		 		   --add-metadata --metadata-from-title "%(title)s" \
		 		   --postprocessor-args \
		 		   "-acodec libmp3lame" \
		 		   -o "${music_dir}/${title}.%(ext)s"
done <<EOF
$(youtube-dl ${pl_url} --flat-playlist  --get-id -e)
EOF
