#!/bin/sh
# Downloads my personal favorite songs/albums
# These songs take alot of space


dir=${HOME}/Music
urls="
https://www.youtube.com/watch?v=QAOBbPnI5-g   Metallica - Master Of Puppets
https://www.youtube.com/watch?v=QBJ1OzMtNwg   Metallica - Ride The Lightning
https://www.youtube.com/watch?v=aMH7yp1EXw8   Metallica - And Justice For All
https://www.youtube.com/watch?v=a41bERTFBUI   Metallica - Ecstacy Of Gold
https://www.youtube.com/watch?v=c8qrwON1-zE   Metallica - Orion
https://www.youtube.com/watch?v=_t6-KdRwC_U   Equilibrium - Kurzes Epos
https://www.youtube.com/watch?v=LJRf19VcwUU   Equilibrium - Aufbruch
https://www.youtube.com/watch?v=qQU4vatuT6g   Equilibrium - Mana
https://www.youtube.com/watch?v=7-i-LhRudP4   Stratovarius - Stratofortress
https://www.youtube.com/watch?v=KHVP2anxbH8   Stratovarius - Holy Light
https://www.youtube.com/watch?v=aJZJVtBPl_E   Tiluland - Axes Of The Universe
https://www.youtube.com/watch?v=7elDoQMH48k   Savatage - The Storm
https://www.youtube.com/watch?v=HOVQ2fkQI5A   Running Wild - Siberian Winter
https://www.youtube.com/watch?v=-uRmn0aUMK4   Exmortus - Moonlight Sonata (Act 3)
https://www.youtube.com/watch?v=tBdtJzeCkJ4   Ascension - Orb of the Moons
https://www.youtube.com/watch?v=4xAu2Ay15fs   Galneryus - Vetelgyus
https://www.youtube.com/watch?v=9XlNbQv_Rg4   Warmen - Salieri Strikes Back
https://www.youtube.com/watch?v=JGv6gzImsfg   Cain's Offering - I Am Legion (Instrumental)
https://www.youtube.com/watch?v=r8n6j21UJMo   Dark Forest - Heart of the Rose
"


cmd=""
GetYTDL() {
	if ! command -v youtube-dl >/dev/null; then
		printf "'youtube-dl' is not installed, getting youtube-dl\n"
		if command -v curl >/dev/null; then
			cmd="$(curl -Ls https://yt-dl.org/downloads/latest/youtube-dl)"
		elif command -v wget >/dev/null; then
			cmd="$(wget -qO- https://yt-dl.org/downloads/latest/youtube-dl)"
		else
			printf 'Cannot download youtube-dl, curl and wget is not installed...\n'
			exit
		fi
	else
		cmd="$(
			while IFS='' read line; do
				printf '%b\n' "${line}"
			done < $(command -v youtube-dl)
		)"
	fi
}


main() {
	GetYTDL

	printf 'NOTICE: I DO NOT OWN ANY OF THIS MUSIC, CREDIT GOES TO THEIR RESPECTIVE ARTIST/BANDS/MUSICIANS\n'

	[ ! -d "${dir}" ] &&
		mkdir --parents "${dir}"


	printf '%b\n' "${urls}" | while read line; do
		[ -z "${line}" ] && continue

		url=${line%% *}
		title=${line#${url}}
		title=${title#${title%%[! ]*}}


		if [ ! -f "${dir}/${title}.mp3" ]; then
			printf 'Downloading %s....\n' "${title}"
			if command -v python >/dev/null; then
				python -c "${cmd}" --extract-audio --audio-format mp3 "${url}" -o "${dir}/${title}.mp3"
			elif command -v python3 >/dev/null; then
				python3 -c "${cmd}" --extract-audio --audio-format mp3 "${url}" -o "${dir}/${title}.mp3"
			fi
		else
			printf '%s.mp3 exists, skipping...\n' "${title}"
		fi
	done
}
main
