#!/bin/sh
music_dir="${HOME}/Music"
pl_url="https://www.youtube.com/playlist?list=PLRV1hc8TIW-7znQIWaVarxdUxf7lskmBc"

# Check if youtube-dl is installed
[ "$(command -v youtube-dl)" ] || {
	printf 'ERROR: `youtube-dl` is not installed\n' >&2
	exit 1
}

# Check if ${music_dir} exist as a directory
[ -d "${music_dir}" ] || {
	printf 'Warning: `%s` does not exist, create [Y\\n] ' "${music_dir}"
	read input
	case "${input}" in
		[Yy][Ee][Ss]|[Yy]|"") ;;
		*) printf 'Exiting...\n' && exit 1 ;;
	esac
}

printf 'Getting urls...\n'
while read title; do
	read id
	url="https://www.youtube.com/watch?v=${id}"
	file="${music_dir%/}/${title}.mp3"
	[ -f "${file}" ] ||
		youtube-dl "${url}" --extract-audio --audio-format mp3 -o "${file}"
done << EOF
$(youtube-dl ${pl_url} --flat-playlist  --get-id -e)
EOF
