#!/bin/sh
# This script returns an icon and network variable
# Dependencies:
#   * Posix compliant shell (screw off fish)

disconnect=""
ethernet=""
wifi=""

get_networkmanager(){
	nmcli device | while read line; do
		case ${line} in
			*\ connected\ *)
				case "${line}" in
					*\ ethernet\ *) printf "${ethernet}" ;;
					*\ wifi\ *)     printf "${wifi}" ;;
				esac

				line="${line#[0-9a-zA-z]* }"
				line="${line#${line%%[! ]*}}"
				network="${line#*connected}"
				printf ' %b' "${network#${network%%[! ]*}}"
				;;
		esac
	done
}


# Needs Updating
get_connman(){
	old_ifs=${IFS}
	IFS='
	'

	for line in $(connmanctl services); do
		if [ ! "${line##[*]*}" ]; then
			printf '  '

			network="${line#${line% *} }"
			network="${network%%_*}"
			if [ "${network}" = "wifi" ]; then
				printf "${wifi} "
			elif [ "${network}" = "ethernet" ]; then
				printf "${ethernet} "
			fi

			line="${line#* }"
			line="${line% *}"
			line="${line%${line##*[! ]}}"
			printf "${line}"
		fi
	done


	IFS=${old_ifs}
}


main() {
	if pidof NetworkManager >/dev/null; then
		network=$(get_networkmanager)
	elif pidof connmand >/dev/null; then
		network=$(get_connman)
	else
		network="${disconnect} No Network Manager"
	fi

	if [ -n "${network}" ]; then
		printf '%b\n' "${network#  }"
	else
		printf '%b Not Connected\n' "${disconnect}"
	fi
}
main
