#!/bin/sh

# This script returns an $icon and $volume variable
StartPulseaudio() {
	pidof pulseaudio >/dev/null || setsid --fork pulseaudio --start --exit-idle-time=-1
}


StartPipewire() {
	pidof pipewire >/dev/null               || setsid --fork pipewire
	pidof pipewire-pulse >/dev/null         || setsid --fork pipewire-pulse
	pidof pipewire-media-session >/dev/null || setsid --fork pipewire-media-session
}

CheckProcess() {
	if command -v pipewire >/dev/null && command -v pipewire-pulse >/dev/null && command -v pipewire-media-session >/dev/null; then
		StartPipewire
	elif command -v pulseaudio >/dev/null; then
		StartPulseaudio
	fi
}

main() {
	CheckProcess
	pactl list sinks | while read line; do
		case "${line}" in
			Volume*)
				vol="${line#*/}"
				vol="${vol%%/*}"
				vol="${vol%[%]*}"
				printf '%b%%\n' "${vol#${vol%%[! ]*}}"
				break
				;;
			Mute*no)
				printf ' '
				;;

			Mute*yes)
				printf ' '
				;;
		esac
	done
}
main
