#!/bin/sh

# This script returns an $icon and $volume variable
check_process()
{
	if [ "$(command -v pipewire)" ] && [ "$(command -v pipewire-pulse)" ] && [ "$(command -v pipewire-media-session)" ]; then
		pidof pipewire >/dev/null               || setsid --fork pipewire
		pidof pipewire-pulse >/dev/null         || setsid --fork pipewire-pulse
		pidof pipewire-media-session >/dev/null || setsid --fork pipewire-media-session
	elif command -v pulseaudio >/dev/null; then
		pidof pulseaudio >/dev/null || setsid --fork pulseaudio --start --exit-idle-time=-1
	fi
}


pulse_droidcam()
{
	if [ ! "$(ps -aux | grep 'droidcam-cli' | grep -E '[-]a')" ] || [ ! "$(pidof pulseaudio)" ]; then
		return
	fi

	load_module=true

	old_ifs=${IFS}
	IFS='
	'

	for line in $(pactl list); do
		if [ -z "${line##*droidcam_audio*}" ]; then
			load_module=false
			break
		fi
	done

	if ${load_module}; then
		pactl load-module module-alsa-source device=hw:Loopback,1,0 source_properties=device.description=droidcam_audio >/dev/null
	fi

	for line in $(pactl list); do
		if [ -z "${line##*droidcam_audio*}" ]; then
			pactl set-default-source 'alsa_input.hw_Loopback_1_0' >/dev/null
			break
		fi
	done

	IFS=${old_ifs}
	unset load_module
}


main()
{
	check_process
	pulse_droidcam
	while read line; do
		case "${line}" in
			'Default Sink'*)
				default_sink="${line#*: }"
				break
				;;
		esac
	done <<-EOF
	$(pactl info)
	EOF

	while read line; do
		case "${line}" in
			*"${default_sink}")
				while true; do
					read line
					case "${line}" in
						*'Mute'*)
							if [ ! "${line##*no}" ]; then
								printf '%b ' ''
							else
								printf '%b ' ''
							fi
							;;
						*'Volume'*)
							volume="${line#*/}"
							volume="${volume%% /*}"
							volume="${volume#${volume%%[! ]*}}"
							printf '%s\n' "${volume}"
							break
							;;
					esac
				done
				break
				;;
		esac
	done <<-EOF
	$(pactl list sinks)
	EOF
}
main
