#!/bin/sh
# @name test.sh
# @description Run a Xephyr session to test AwesomeWM
# Use Ctrl-c to stop it
display=:1

# @section Color definitions
color_error="\033[1;31m"
color_reset="\033[m"

# @section Exit code definitions
code_command_not_found=127

# @section Signal code definitions
sig_term=15


# @description Prints a formated error to stderr
# @arg $1 string The error message
err() {
	printf "[%bERR%b] %s\n" "${color_error}" "${color_reset}" "${1}" >&2
}


# @description Checks for a dependency and prints out an error and exit if it's
# missing
# @arg $1 string The dependency to check
check_dependency() {
	if ! [ "$(command -v ${1})" ]; then
		err "Command '${dep}' not found"
		exit ${code_command_not_found}
	fi
}


# @description The main function
main() {
	for dep in Xephyr awesome kill; do
		check_dependency "${dep}"
	done
	Xephyr ${display} -resizeable &
	DISPLAY=${display} awesome
}

main
